 # uncomment below lines to use CML

name: DVC-project
 
on: [push]
 
jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: deploy
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner \
          --cloud aws \
          --cloud-region us-east \
          --cloud-type=t2.medium \
          --labels=cml-runner
 
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: docker://iterativeai/cml:0-dvc2-base1
 
    steps:
    - uses: actions/checkout@v3
    - name: "automatic ci/cd"
      env:
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        dvc repro -f
        echo "# REPORTS" >> report.md
        echo "## metrics" >> report.md
        cat scores.json >> report.md
        cml-send-comment report.md
